[build-system]
requires = ["setuptools>=61", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "eppoPynder"
version = "2.0.0"
description = "Python interface to the EPPO Database and Public APIs"
readme = "README.md"
authors = [
    { name = "Lorenzo Copelli" },
    { name = "Dayana Stephanie Buzle" },
    { name = "Rafael Vieira" },
    { name = "Agata Kaczmarek" },
    { name = "Luca Belmonte" }
]
maintainers = [
    { name = "Luca Belmonte", email = "luca.belmonte@efsa.europa.eu" }
]
license = "EUPL-1.2"
license-files = ["LICENSE"]
requires-python = ">=3.11"
dependencies = [
    "numpy>=2.0",
    "pandas>=2.2",
    "requests>=2.32",
    "python-dotenv>=1.0"
]

[project.optional-dependencies]
dev = [
    "coverage>=7.6",
    "pytest>=8.0",
]

[project.urls]
"Homepage" = "https://github.com/openefsa/eppoPynder"
"Repository" = "https://github.com/openefsa/eppoPynder"
"Bug Tracker" = "https://github.com/openefsa/eppoPynder/issues"

[tool.setuptools]
package-dir = {"" = "src"}

[tool.setuptools.packages.find]
where = ["src"]
