name: Run tests and upload coverage

on: 
  push:
    branches:
      - dev  # Trigger the workflow on push to the dev branch
  pull_request:
    branches:
      - dev  # Trigger the workflow on pull requests to the dev branch

jobs:
  test:
    name: Run tests and collect coverage
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4

      - name: Install dependencies
        run: |
          pip install pytest-cov codecov
          pip install -r requirements.txt

      - name: Set PYTHONPATH to src
        run: echo "PYTHONPATH=$(pwd)/src" >> $GITHUB_ENV  # Set PYTHONPATH to the 'src' directory
          
      - name: Run tests
        run: pytest --cov-branch --cov-report=xml

      - name: Upload results to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
